name: Run Playwright + Cucumber tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests in parallel
        run: npx cucumber-js --parallel 4 --retry 2
      
      - name: Run tests
        run: npm test
        env:
          CI: true
